import { runGit } from "./runner.js";
import { buildGitDateArgs } from "./log.js";
import type { DateFilter, DiffStat } from "./types.js";

/**
 * Built-in noisy file patterns representing high-churn, low-signal files.
 */
export const DEFAULT_NOISY_PATTERNS: RegExp[] = [
  // Package lockfiles across package managers
  /(?:^|\/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|go\.sum|composer\.lock|Gemfile\.lock|flake\.lock|poetry\.lock|Pipfile\.lock|bun\.lockb?|mix\.lock|pubspec\.lock|packages\.lock\.json)$/i,

  // Build artifacts, bundles, sourcemaps, and compiler metadata
  /\.min\.(js|css)$/i,
  /\.bundle\.(js|css)$/i,
  /\.map$/i,
  /\.d\.ts\.map$/i,
  /(?:^|\/)\.tsbuildinfo$/i,
  /\.tsbuildinfo$/i,

  // Test snapshots and autogenerated snapshot fixtures
  /\.snap(?:shot)?(?:\.json)?$/i,

  // Binary assets, images, media, fonts, archives, and compiled binaries
  /\.(png|jpe?g|gif|svg|ico|webp|avif|bmp|tiff|heic|psd|ai)$/i,
  /\.(mp3|mp4|wav|ogg|webm|flac|m4a|mov|avi|mkv)$/i,
  /\.(woff2?|eot|ttf|otf)$/i,
  /\.(wasm|pdf|zip|gz|tar|tgz|rar|7z|bz2|xz|iso|dmg|exe|dll|so|dylib|bin|jar)$/i,
];

/**
 * Convert a glob pattern (e.g., "*.lock", "dist/**", "fixtures/*.json") into a regular expression.
 */
export function globToRegex(pattern: string): RegExp {
  const normalized = pattern.trim().replace(/\\/g, "/");

  if (!normalized) {
    return /^$/;
  }

  let regexStr = "";
  let i = 0;
  const hasSlash = normalized.includes("/");

  while (i < normalized.length) {
    const c = normalized[i];
    if (c === "*" && normalized[i + 1] === "*") {
      if (normalized[i + 2] === "/") {
        regexStr += "(?:.*\/)?";
        i += 3;
      } else {
        regexStr += ".*";
        i += 2;
      }
    } else if (c === "*") {
      regexStr += "[^/]*";
      i++;
    } else if (c === "?") {
      regexStr += "[^/]";
      i++;
    } else if (["[", "]", "(", ")", "{", "}", ".", "+", "^", "$", "|"].includes(c)) {
      regexStr += `\\${c}`;
      i++;
    } else {
      regexStr += c;
      i++;
    }
  }

  if (hasSlash) {
    if (normalized.startsWith("/")) {
      return new RegExp(`^${regexStr.slice(1)}`, "i");
    }
    return new RegExp(`(?:^|\/)${regexStr}$`, "i");
  }

  return new RegExp(`(?:^|\/)${regexStr}$`, "i");
}

/**
 * Determines whether a file path matches any custom ignore pattern.
 */
export function matchesCustomIgnore(filePath: string, customPatterns?: string[]): boolean {
  if (!customPatterns || customPatterns.length === 0) {
    return false;
  }

  const normalized = filePath.replace(/\\/g, "/").replace(/^\.\//, "");
  for (const pattern of customPatterns) {
    if (!pattern || typeof pattern !== "string") continue;
    const re = globToRegex(pattern);
    if (re.test(normalized)) {
      return true;
    }
  }
  return false;
}

/**
 * Checks if a file is considered noisy or ignored for AI diff context.
 */
export function isNoisyFile(
  filePath: string,
  customPatterns?: string[],
  smartFilterEnabled = true,
): boolean {
  if (matchesCustomIgnore(filePath, customPatterns)) {
    return true;
  }

  if (smartFilterEnabled) {
    const normalized = filePath.replace(/\\/g, "/").replace(/^\.\//, "");
    return DEFAULT_NOISY_PATTERNS.some((pattern) => pattern.test(normalized));
  }

  return false;
}

export const shouldIgnoreDiff = isNoisyFile;

/**
 * Returns a priority score (0-100) for a given file path based on its architectural and signal importance.
 * Higher scores are prioritized when truncating diffs to fit within token/line budgets.
 */
export function getFilePriority(filePath: string): number {
  const normalized = filePath.replace(/\\/g, "/").replace(/^\.\//, "").toLowerCase();
  const baseName = normalized.split("/").pop() || "";

  // 1. Critical Architecture, Manifests & Root Configuration (Score: 100)
  if (
    /^(package\.json|tsconfig(?:\..+)?\.json|cargo\.toml|go\.mod|go\.work|pyproject\.toml|setup\.py|pom\.xml|build\.gradle(?:\.kts)?|settings\.gradle(?:\.kts)?|makefile|cmakelists\.txt|dockerfile(?:\..+)?|docker-compose(?:\..+)?\.ya?ml|agents\.md)$/i.test(
      baseName,
    ) ||
    normalized === "architecture.md" ||
    /^\.github\/workflows\/.*\.ya?ml$/i.test(normalized) ||
    /^\.gitlab-ci\.ya?ml$/i.test(normalized)
  ) {
    return 100;
  }

  // 2. Localization / Translations (Score: 10) - check early before data/text
  if (/^(locales|i18n|translations|lang)\//i.test(normalized) || /\.(po|pot)$/i.test(baseName)) {
    return 10;
  }

  // 3. Data Fixtures, Mocks & Test Data (Score: 20)
  if (/^(fixtures|mocks|__mocks__|__fixtures__|testdata|samples|examples)\//i.test(normalized)) {
    return 20;
  }

  // 4. Stylesheets & UI Markup (Score: 25)
  if (/\.(css|scss|sass|less|html|htm)$/i.test(baseName)) {
    return 25;
  }

  // 5. Tooling, Build Scripts, Linters (Score: 30)
  if (
    /^(scripts|tools|bin|benchmarks)\//i.test(normalized) ||
    /^(webpack|vite|rollup|eslint|prettier|jest|vitest|turbo|babel)\.config\./i.test(baseName) ||
    /^\.(eslintrc|prettierrc|babelrc)/i.test(baseName)
  ) {
    return 30;
  }

  // 6. Tests & Test Specs (Score: 40)
  if (
    /^(test|tests|spec|specs|__tests__)\//i.test(normalized) ||
    /\.(test|spec)\.(ts|tsx|js|jsx|py|rb|mjs|cjs)$/i.test(baseName) ||
    /_test\.(go|rs|py)$/i.test(baseName) ||
    /^test_.*\.py$/i.test(baseName)
  ) {
    return 40;
  }

  // 7. General Documentation & Guides (Score: 50)
  if (/^docs\//i.test(normalized) || /\.(mdx|rst|adoc|txt)$/i.test(baseName) || (/\.md$/i.test(baseName) && baseName !== "readme.md")) {
    return 50;
  }

  // 8. API Schemas & Major Root Documentation (Score: 60)
  if (
    /^(readme\.md|openapi(?:\..+)?\.ya?ml|openapi(?:\..+)?\.json|swagger(?:\..+)?\.ya?ml|swagger(?:\..+)?\.json)$/i.test(
      baseName,
    ) ||
    /\.(proto|graphql|prisma)$/i.test(baseName)
  ) {
    return 60;
  }

  // 9. Core Module Entrypoints (Score: 90)
  if (
    /^(index|main|app|server|mod|lib)\.(ts|js|jsx|tsx|go|rs|py|rb|php|cs|swift|kt|c|cpp|h)$/i.test(
      baseName,
    ) ||
    baseName === "__init__.py"
  ) {
    return 90;
  }

  // 10. Primary Core Source Code (in src/, lib/, core/, app/, pkg/, internal/) (Score: 80)
  if (
    /^(src|lib|core|app|internal|pkg|packages|crates)\//i.test(normalized) &&
    /\.(ts|tsx|js|jsx|rs|go|py|c|cpp|h|hpp|java|kt|swift|rb|php|cs|proto|graphql|prisma|sql)$/i.test(
      baseName,
    )
  ) {
    return 80;
  }

  // 11. General Source Code (Score: 70)
  if (/\.(ts|tsx|js|jsx|rs|go|py|c|cpp|h|hpp|java|kt|swift|rb|php|cs|sh|bash|zsh)$/i.test(baseName)) {
    return 70;
  }

  // Default priority for other files
  return 20;
}

export interface DiffOptions {
  maxPatchLines?: number;
  maxLines?: number;
  smartDiffFilter?: boolean;
  diffIgnorePatterns?: string[];
}

interface ParsedFileDiff {
  filePath: string;
  lines: string[];
  priority: number;
  isNoisy: boolean;
  order: number;
}

/**
 * Extracts and filters git diff patches, intelligently ignoring high-churn noisy files
 * and prioritizing high-signal architecture/source files when line budgets are constrained.
 */
export async function fetchDiffPatches(
  repoPath: string,
  branches: string[],
  filter: DateFilter = {},
  maxPatchLinesOrOptions: number | DiffOptions = 300,
  maybeOptions?: DiffOptions,
): Promise<string> {
  const maxPatchLines =
    typeof maxPatchLinesOrOptions === "number"
      ? maxPatchLinesOrOptions
      : maxPatchLinesOrOptions?.maxPatchLines ?? maxPatchLinesOrOptions?.maxLines ?? 300;

  const options: DiffOptions =
    typeof maxPatchLinesOrOptions === "object" ? maxPatchLinesOrOptions : maybeOptions ?? {};

  const smartFilter = options.smartDiffFilter ?? true;
  const ignorePatterns = options.diffIgnorePatterns ?? [];

  const dateArgs = buildGitDateArgs(filter);
  const targetBranch = branches[0] || "HEAD";

  // Run git log with unified patch diffs (-p) and 2 lines of context (-U2)
  const res = await runGit(["log", targetBranch, ...dateArgs, "-p", "-U2", "--no-color"], repoPath);
  if (res.exitCode !== 0 || !res.stdout) {
    return "";
  }

  const rawLines = res.stdout.split("\n");
  const fileDiffs: ParsedFileDiff[] = [];
  let currentFile: ParsedFileDiff | null = null;
  let orderCounter = 0;

  for (const line of rawLines) {
    // Check file header in diff output: "diff --git a/... b/..."
    const diffHeaderMatch = line.match(/^diff --git (?:a\/(.+?)|"a\/(.+?)") (?:b\/(.+?)|"b\/(.+?)")$/);
    if (diffHeaderMatch) {
      if (currentFile) {
        fileDiffs.push(currentFile);
      }

      let filePath =
        diffHeaderMatch[3] ||
        diffHeaderMatch[4] ||
        diffHeaderMatch[1] ||
        diffHeaderMatch[2] ||
        "";
      if (filePath === "/dev/null" || filePath === "dev/null") {
        filePath = diffHeaderMatch[1] || diffHeaderMatch[2] || filePath;
      }

      const noisy = isNoisyFile(filePath, ignorePatterns, smartFilter);
      const priority = getFilePriority(filePath);

      currentFile = {
        filePath,
        lines: [line],
        priority,
        isNoisy: noisy,
        order: orderCounter++,
      };
      continue;
    }

    if (currentFile) {
      // Skip index and mode lines to save token budget
      if (line.startsWith("index ") || line.startsWith("old mode ") || line.startsWith("new mode ")) {
        continue;
      }
      currentFile.lines.push(line);
    }
  }

  if (currentFile) {
    fileDiffs.push(currentFile);
  }

  // Filter out noisy files
  const activeFileDiffs = fileDiffs.filter((f) => !f.isNoisy);

  if (activeFileDiffs.length === 0) {
    return "";
  }

  // Count total lines across all active file diffs
  const totalActiveLines = activeFileDiffs.reduce((sum, f) => sum + f.lines.length, 0);

  if (totalActiveLines <= maxPatchLines) {
    return activeFileDiffs.map((f) => f.lines.join("\n")).join("\n");
  }

  // Prioritize files by signal score (descending), keeping original relative order as tiebreaker
  const prioritized = [...activeFileDiffs].sort((a, b) => b.priority - a.priority || a.order - b.order);

  const outputSections: string[] = [];
  let remainingBudget = maxPatchLines;
  let omittedFileCount = 0;

  for (const file of prioritized) {
    if (remainingBudget <= 0) {
      omittedFileCount++;
      continue;
    }

    if (file.lines.length <= remainingBudget) {
      outputSections.push(file.lines.join("\n"));
      remainingBudget -= file.lines.length;
    } else if (remainingBudget >= 6) {
      // Partially include this high-priority file
      const partialLines = file.lines.slice(0, remainingBudget - 1);
      partialLines.push(`\n... [Diff for ${file.filePath} truncated to fit line budget] ...`);
      outputSections.push(partialLines.join("\n"));
      remainingBudget = 0;
    } else {
      omittedFileCount++;
    }
  }

  if (omittedFileCount > 0) {
    outputSections.push(`\n... [Diff truncated: ${omittedFileCount} lower-priority file(s) omitted to fit budget] ...`);
  }

  return outputSections.join("\n");
}

/**
 * Fetches git diffstat summary and patches for a given repository and branch.
 */
export async function fetchDiffStat(
  repoPath: string,
  branches: string[],
  filter: DateFilter = {},
  maxLinesOrOptions: number | DiffOptions = 200,
  maybeOptions?: DiffOptions,
): Promise<DiffStat | undefined> {
  const maxLines =
    typeof maxLinesOrOptions === "number"
      ? maxLinesOrOptions
      : maxLinesOrOptions?.maxLines ?? 200;

  const options: DiffOptions =
    typeof maxLinesOrOptions === "object" ? maxLinesOrOptions : maybeOptions ?? {};

  const smartFilter = options.smartDiffFilter ?? true;
  const ignorePatterns = options.diffIgnorePatterns ?? [];

  const dateArgs = buildGitDateArgs(filter);
  const targetBranch = branches[0] || "HEAD";

  // Run git log with diffstat
  const res = await runGit(["log", targetBranch, ...dateArgs, "--stat"], repoPath);
  if (res.exitCode !== 0 || !res.stdout) {
    return undefined;
  }

  const lines = res.stdout.split("\n");
  const fileStats: Array<{ path: string; insertions: number; deletions: number }> = [];
  let totalFiles = 0;
  let totalInsertions = 0;
  let totalDeletions = 0;

  for (const line of lines) {
    // Matches standard git diffstat summary: " 3 files changed, 20 insertions(+), 5 deletions(-)"
    const summaryMatch = line.match(/(\d+)\s+files?\s+changed(?:,\s+(\d+)\s+insertions?\(\+\))?(?:,\s+(\d+)\s+deletions?\(-\))?/i);
    if (summaryMatch) {
      totalFiles += parseInt(summaryMatch[1] || "0", 10);
      totalInsertions += parseInt(summaryMatch[2] || "0", 10);
      totalDeletions += parseInt(summaryMatch[3] || "0", 10);
      continue;
    }

    const fileMatch = line.match(/^\s*(.+?)\s*\|\s*(\d+)\s*([\+\-]*)/);
    if (fileMatch) {
      const path = (fileMatch[1] ?? "").trim();
      if (isNoisyFile(path, ignorePatterns, smartFilter)) {
        continue;
      }

      const count = parseInt(fileMatch[2] ?? "0", 10);
      const symbols = fileMatch[3] ?? "";
      const plusCount = (symbols.match(/\+/g) || []).length;
      const minusCount = (symbols.match(/\-/g) || []).length;
      const totalSymbols = plusCount + minusCount || 1;

      const ins = Math.round((plusCount / totalSymbols) * count);
      const del = count - ins;

      fileStats.push({ path, insertions: ins, deletions: del });
    }
  }

  // Sort file stats by priority so the top 30 entries represent the highest architectural value
  fileStats.sort((a, b) => getFilePriority(b.path) - getFilePriority(a.path));

  const truncatedSummary = lines
    .filter((l) => {
      const fm = l.match(/^\s*(.+?)\s*\|\s*\d+/);
      if (fm) {
        return !isNoisyFile(fm[1]?.trim() || "", ignorePatterns, smartFilter);
      }
      return true;
    })
    .slice(0, maxLines)
    .join("\n");

  const diffPatches = await fetchDiffPatches(
    repoPath,
    branches,
    filter,
    {
      maxPatchLines: maxLines * 2,
      smartDiffFilter: smartFilter,
      diffIgnorePatterns: ignorePatterns,
    },
  );

  return {
    filesChangedCount: totalFiles || fileStats.length,
    insertions: totalInsertions,
    deletions: totalDeletions,
    fileStats: fileStats.slice(0, 30),
    diffSummary: truncatedSummary,
    diffPatches: diffPatches || undefined,
  };
}
